# Generated by Django 4.2.3 on 2023-07-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=221, null=True, unique=True)),
                ('full_name', models.CharField(max_length=221)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
